<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Second_ASP_EF_MVC.Domain\Second_ASP_EF_MVC.Domain.csproj" />
    <ProjectReference Include="..\Second_ASP_EF_MVC.Infrastructure\Second_ASP_EF_MVC.Infrastructure.csproj" />
  </ItemGroup>

</Project>
