<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Core" Version="1.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.30">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Second_ASP_EF_MVC.Application\Second_ASP_EF_MVC.Application.csproj" />
    <ProjectReference Include="..\Second_ASP_EF_MVC.Domain\Second_ASP_EF_MVC.Domain.csproj" />
    <ProjectReference Include="..\Second_ASP_EF_MVC.Infrastructure\Second_ASP_EF_MVC.Infrastructure.csproj" />
  </ItemGroup>

</Project>
